{{- if and .Values.flower.enabled .Values.flower.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flower-chart.fullname" . }}-ingress
  namespace: {{ include "flower-chart.namespace" . }}
  labels:
    {{- include "flower-chart.labels" . | nindent 4 }}
  {{- with .Values.flower.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.flower.ingress.ingressClassName }}
  ingressClassName: {{ .Values.flower.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.flower.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.flower.ingress.hostname | quote }}
      secretName: flower-tls
  {{- end }}
  rules:
    - host: {{ .Values.flower.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flower-chart.fullname" . }}
                port:
                  number: {{ .Values.flower.service.port }}
{{- end }}

