{{- if and .Values.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-pv
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: /data/postgres
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-pvc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ include "postgresql.fullname" . }}-pv
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}

