{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    tier: db
spec:
  serviceName: db
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgresql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgresql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: db
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName | default "tatarlang-app-config" }}
            - secretRef:
                name: {{ .Values.secretName | default "tatarlang-db-secret" }}
          {{- if and .Values.persistence.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if and .Values.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "postgresql.fullname" . }}-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    tier: db
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: db
  selector:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: db
{{- end }}

