{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "tatarlang-chart.selectorLabels" . | nindent 6 }}
      tier: backend
  template:
    metadata:
      labels:
        {{- include "tatarlang-chart.selectorLabels" . | nindent 8 }}
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "tatarlang-chart.fullname" . }}-app-config
            - secretRef:
                name: {{ include "tatarlang-chart.fullname" . }}-db-secret
            - secretRef:
                name: {{ include "tatarlang-chart.fullname" . }}-celery-secret
          {{- if .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.resources }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- end }}
{{- end }}

