apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-app-config
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.postgres.db | quote }}
  POSTGRES_HOST: {{ .Values.config.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.config.postgres.port | quote }}
  DJANGO_SETTINGS_MODULE: {{ .Values.config.django.settingsModule | quote }}
  REACT_APP_API_URL: {{ .Values.config.frontend.apiUrl | quote }}

