{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
    tier: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      {{- include "tatarlang-chart.selectorLabels" . | nindent 6 }}
      tier: rabbitmq
  template:
    metadata:
      labels:
        {{- include "tatarlang-chart.selectorLabels" . | nindent 8 }}
        tier: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.rabbitmq.service.httpPort }}
              name: http
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "tatarlang-chart.fullname" . }}-rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "tatarlang-chart.fullname" . }}-rabbitmq-secret
                  key: RABBITMQ_PASS
          {{- if .Values.rabbitmq.resources }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
    tier: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
    - name: http
      port: {{ .Values.rabbitmq.service.httpPort }}
      targetPort: {{ .Values.rabbitmq.service.httpPort }}
  selector:
    {{- include "tatarlang-chart.selectorLabels" . | nindent 4 }}
    tier: rabbitmq
{{- end }}

