apiVersion: v1
kind: Namespace
metadata:
  name: tatarlang
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tatarlang-app-config
  namespace: tatarlang
data:
  POSTGRES_DB: tatarlang
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  DJANGO_SETTINGS_MODULE: tatarlang.settings
  REACT_APP_API_URL: "https://tatarlang.local/api/v1"
---
apiVersion: v1
kind: Secret
metadata:
  name: tatarlang-db-secret
  namespace: tatarlang
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: tatarlang-rabbitmq-secret
  namespace: tatarlang
type: Opaque
stringData:
  RABBITMQ_USER: "admin"
  RABBITMQ_PASS: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: tatarlang-celery-secret
  namespace: tatarlang
type: Opaque
stringData:
  CELERY_BROKER_URL: "amqp://admin:admin@rabbitmq:5672//"
