{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-chart.fullname" . }}
  namespace: {{ include "vault-chart.namespace" . }}
  labels:
    {{- include "vault-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vault.service.type }}
  ports:
    - port: {{ .Values.vault.service.port }}
      targetPort: {{ .Values.vault.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "vault-chart.selectorLabels" . | nindent 4 }}
{{- end }}

