apiVersion: v2
name: rabbitmq
description: RabbitMQ subchart for Tatarlang using Bitnami chart
type: application
version: 0.1.0
appVersion: "3-management"
dependencies:
  - name: rabbitmq
    version: 14.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled

